const accordionData = [
  {
    id: '68b67783b5e01f896a08ddd2',
    title: 'Dolor qui sit reprehenderit elit amet aute Lorem.',
    description:
      'Dolor magna et do amet duis laborum nulla eiusmod. Occaecat enim officia anim velit id nisi veniam nostrud dolor enim aliquip aliqua ullamco. Aute nisi duis ut anim id incididunt ea ullamco.\r\nMagna culpa non commodo eu proident sit aliquip laboris excepteur tempor. Duis mollit ut excepteur magna reprehenderit sint. Reprehenderit magna consectetur laborum culpa aliquip enim qui quis Lorem id deserunt non. Quis culpa occaecat eiusmod Lorem adipisicing aute Lorem cillum consectetur do cillum. Velit pariatur dolore cupidatat dolor occaecat. Consequat dolore quis exercitation culpa minim ullamco qui nulla velit. Ex dolor deserunt consequat dolor mollit id aliquip consequat commodo.\r\nFugiat esse velit est consectetur consequat ad do fugiat consectetur ex velit exercitation. Deserunt deserunt minim anim consectetur occaecat excepteur ullamco exercitation id ut do nulla nostrud. Anim aute velit duis sit laborum laboris ut id nisi labore. Velit anim non ipsum irure aute qui esse. Commodo nostrud consequat incididunt deserunt reprehenderit reprehenderit sit sunt commodo veniam aliqua ullamco mollit. Voluptate excepteur culpa labore culpa minim laboris ad irure occaecat. Irure non esse nulla ea.\r\nVelit consequat sint anim et minim occaecat mollit officia excepteur commodo nulla eu nostrud. Nostrud do excepteur elit quis. Consequat Lorem exercitation ad incididunt tempor ipsum fugiat laboris nostrud consequat esse. Veniam deserunt ex adipisicing mollit ut culpa.\r\n',
  },
  {
    id: '68b67783e958f4a70445f525',
    title:
      'Sunt duis consectetur officia pariatur reprehenderit consequat amet adipisicing irure do labore.',
    description:
      'Amet cillum sint ad exercitation excepteur esse dolore reprehenderit dolore. Pariatur sint irure minim reprehenderit incididunt nisi minim in Lorem ut duis duis. Dolore dolor duis ea consequat velit excepteur duis et ullamco amet minim elit aute ut. Voluptate cillum consequat mollit do commodo cupidatat veniam exercitation.\r\nVelit amet aliqua occaecat ut reprehenderit esse. Ullamco sint duis incididunt anim Lorem consectetur fugiat amet amet exercitation dolor tempor voluptate. Minim ut cupidatat id est consequat. Nostrud ullamco consequat qui qui est ipsum. Occaecat proident anim deserunt duis veniam. Deserunt incididunt cillum velit commodo occaecat dolor occaecat. Quis exercitation occaecat do officia quis labore ut velit sint dolore.\r\n',
  },
  {
    id: '68b67783411de0b142383c46',
    title: 'Id officia reprehenderit voluptate quis dolor cupidatat eu.',
    description:
      'Enim exercitation ipsum nulla sint. Voluptate sunt mollit duis incididunt adipisicing ut et ea veniam sint cupidatat id. Amet magna incididunt elit do ut ipsum qui aliqua ad exercitation incididunt duis ipsum. Ut magna eu voluptate est anim quis commodo adipisicing ut cillum laborum nostrud veniam adipisicing. Magna anim consequat exercitation eiusmod fugiat nulla aute id enim id nulla cillum non. Elit sunt elit non anim. Non voluptate anim in ad veniam velit id laboris enim id eiusmod do do.\r\nIn minim qui est sunt id. Officia occaecat non do officia exercitation irure magna sunt irure. Reprehenderit sunt sunt laborum est nostrud magna est aliqua pariatur nisi ad laborum sunt laboris. Do amet minim dolore occaecat et velit.\r\nAnim nostrud irure velit ullamco ut sunt sint excepteur amet. Nostrud voluptate ut excepteur sunt deserunt nostrud. Deserunt minim exercitation minim voluptate sint cupidatat eu. Cillum pariatur culpa adipisicing cillum id exercitation adipisicing est ea adipisicing.\r\nAliqua consectetur sunt ullamco et irure sit est amet anim fugiat eiusmod. Consectetur amet cupidatat laborum reprehenderit fugiat labore qui labore mollit nulla Lorem aute anim eu. Eiusmod duis id occaecat aliquip officia sit Lorem sint ea. Elit elit dolore culpa fugiat dolore proident culpa labore consequat ad eiusmod dolore.\r\n',
  },
  {
    id: '68b67783271e4c76a3ffd848',
    title:
      'Occaecat sit eiusmod commodo dolor in consequat ex eu aliquip commodo proident. Quis enim consequat ut dolor.',
    description:
      'Aliquip labore officia irure minim esse esse qui mollit aute incididunt ex aliquip exercitation irure. Incididunt do minim eu id proident mollit anim Lorem deserunt aliqua cupidatat id non. Eu elit aute quis labore. Occaecat pariatur laborum non sunt esse.\r\nMollit laborum ullamco aliqua reprehenderit anim ea amet ipsum in dolore irure laborum aute. Minim excepteur qui nulla aliquip exercitation pariatur Lorem quis. Dolore quis quis incididunt ullamco excepteur officia. Aliqua sunt deserunt tempor aliquip incididunt sit exercitation deserunt dolor nostrud consequat eiusmod exercitation. Duis consectetur ea anim magna esse minim minim exercitation id minim consectetur minim. Deserunt sunt in eu cillum nisi aliquip cupidatat. Mollit consectetur consectetur dolore veniam Lorem pariatur tempor proident enim voluptate nisi exercitation.\r\nEa aliqua ipsum pariatur pariatur proident. Sunt magna est magna officia pariatur ad mollit deserunt qui. Ad ea mollit in laborum magna incididunt enim voluptate duis magna fugiat sint. Lorem ullamco veniam ullamco est et deserunt. Reprehenderit est cillum eu enim fugiat voluptate ipsum commodo. Ipsum duis reprehenderit nostrud non aliquip deserunt minim eiusmod aliqua adipisicing quis mollit mollit do.\r\nDeserunt in dolor ut laboris nisi incididunt. Proident consequat et sit proident qui sit officia aute excepteur qui proident nisi sint in. Lorem adipisicing enim nostrud velit nostrud.\r\n',
  },
  {
    id: '68b67783ab8cf18e093dc378',
    title:
      'Voluptate enim officia pariatur sunt dolore voluptate sint commodo proident fugiat. Non anim duis sint aliquip sit sit.',
    description:
      'Tempor amet duis labore voluptate enim ad. Laboris voluptate cillum minim qui est minim adipisicing quis officia anim cillum exercitation tempor. Cupidatat labore id velit laborum deserunt pariatur do aute eiusmod aute dolore aute nulla est. Nisi consectetur qui cillum Lorem ea labore ipsum dolor mollit. Veniam cillum dolor adipisicing tempor ipsum voluptate eu et aliqua reprehenderit ea tempor. Incididunt incididunt deserunt fugiat culpa mollit anim laboris in qui sit minim. Consectetur et officia aliquip ullamco esse incididunt et non.\r\nDolor ullamco anim laboris dolor sit magna adipisicing mollit ipsum proident in sunt Lorem. Ex id dolore deserunt occaecat labore. Non magna reprehenderit amet ut mollit in non est occaecat minim pariatur aliquip. Irure sint eu ut nisi adipisicing eiusmod exercitation. Magna ea culpa duis sit pariatur ut amet eu. Velit pariatur ad dolor nisi eiusmod et.\r\nReprehenderit excepteur occaecat cupidatat enim aliqua esse voluptate reprehenderit. Ad laborum ad eiusmod veniam eiusmod aliqua ea aliquip proident est cillum incididunt cillum. Ad do ea occaecat esse esse laboris proident nostrud laboris velit.\r\nExercitation incididunt ut consequat cillum sit velit non in do laborum tempor. Dolor ex occaecat mollit laboris. Ex laboris sunt laborum ut officia magna aliquip ut cupidatat cillum laborum anim ut amet. Cillum nulla sunt officia non qui sunt ut adipisicing non consequat duis duis dolore. Nulla culpa consequat deserunt tempor quis id est minim pariatur.\r\n',
  },
  {
    id: '68b6778336063d8bfacc3ca6',
    title: 'Est irure et cupidatat reprehenderit nisi tempor.',
    description:
      'Fugiat tempor nostrud pariatur reprehenderit. Dolor adipisicing eu ut anim quis dolore sint enim qui elit quis elit nisi officia. Tempor Lorem veniam nisi reprehenderit ea sit labore occaecat reprehenderit ullamco. Non aute in reprehenderit labore non amet dolor aliqua sit officia consectetur. Est minim ipsum consectetur commodo nisi Lorem tempor nisi.\r\nNulla aute velit sunt consectetur officia reprehenderit ad ea ad eu et do velit. Laboris labore eiusmod qui amet enim minim consectetur magna id dolor incididunt. Consequat qui veniam amet veniam nulla anim esse. Aliqua sunt ad aute incididunt aute nostrud elit enim incididunt cupidatat veniam excepteur pariatur eu. Duis labore sint pariatur adipisicing laboris fugiat sint aliqua cillum enim consectetur excepteur cupidatat nisi.\r\nNon dolore consectetur nostrud officia voluptate cupidatat velit. Culpa sint magna eiusmod velit occaecat esse officia ipsum quis. Commodo ea laborum laborum nostrud id veniam veniam sint reprehenderit proident consectetur anim non. Culpa veniam incididunt sit id aliquip excepteur aliqua sit ullamco. Minim consectetur et est non proident. Esse in mollit minim consequat tempor ut ut et nostrud. Commodo aliqua ipsum adipisicing eu culpa elit amet.\r\n',
  },
  {
    id: '68b67783f9e89e262d1a8f02',
    title:
      'Consequat dolore ut reprehenderit cillum irure officia nisi commodo adipisicing. Fugiat est duis ullamco nisi dolor proident reprehenderit nostrud velit anim laborum officia eu.',
    description:
      'Ad amet non Lorem do incididunt amet exercitation pariatur culpa occaecat fugiat excepteur occaecat. Aliqua officia aute ad eiusmod quis excepteur commodo officia aliqua laboris. Aliquip mollit eu nulla aliquip Lorem consequat eu sit laborum velit.\r\nDolore sunt enim velit irure commodo anim occaecat mollit nostrud. Elit laboris cupidatat proident consequat nostrud sint veniam incididunt. Anim dolor aliquip deserunt excepteur commodo culpa adipisicing duis tempor est magna minim veniam. Aute irure voluptate ad anim dolor officia sint. Fugiat dolore nulla aliqua aliquip ex minim cillum deserunt amet ad voluptate. Elit excepteur elit qui deserunt velit voluptate aute velit amet laboris adipisicing. Aliquip quis anim amet reprehenderit aliqua tempor ad adipisicing.\r\nTempor cupidatat et proident in. Irure in incididunt aute ipsum excepteur laboris eiusmod magna. Laborum consectetur nostrud aliquip ex commodo duis ex. Dolore eiusmod nostrud reprehenderit commodo.\r\nNulla fugiat culpa pariatur nisi nostrud laboris laboris. Reprehenderit officia minim non Lorem officia elit irure adipisicing. Aliqua minim dolor ut nulla aute do. Reprehenderit aute non tempor qui aliquip est labore nostrud adipisicing velit proident id.\r\n',
  },
]

export default accordionData
